# Generated by Django 3.2.6 on 2021-09-23 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userbase_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today, max_length=8),
        ),
        migrations.AddField(
            model_name='userbase',
            name='image',
            field=models.ImageField(default='images/default.png', help_text='Upload a product image', upload_to='images/', verbose_name='image'),
        ),
    ]
