# Generated by Django 3.2.6 on 2021-09-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_userbase_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=7),
        ),
    ]
