# Generated by Django 3.2.6 on 2021-09-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_userbase_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='gender',
            field=models.CharField(choices=[(0, 'male'), (1, 'female'), (2, 'not specified')], default=2, max_length=7),
        ),
    ]
