# Generated by Django 3.2.6 on 2021-09-27 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_userbase_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbase',
            name='gender',
        ),
    ]
