# Generated by Django 3.2.6 on 2021-09-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_userbase_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbase',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='postcode',
        ),
        migrations.AddField(
            model_name='userbase',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=1),
        ),
    ]
