# Generated by Django 3.2.4 on 2022-01-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20210929_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
