# Generated by Django 3.2.4 on 2022-01-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_users_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required', max_length=40, verbose_name='Title')),
                ('description', models.CharField(help_text='Short As Possiable', max_length=90, verbose_name='Description')),
                ('image', models.ImageField(default='images/default.png', help_text='Upload an Offer image', upload_to='images/', verbose_name='image')),
                ('slug', models.SlugField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
    ]
