# Generated by Django 3.2.4 on 2022-02-09 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_comment_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='producut',
            new_name='product',
        ),
    ]
